### ISSUE TITLE
Question about Cycloneddscxx

### ISSUE THREAD

**Issue by Kyderio** [eclipse-cyclonedds/cyclonedds-cxx#104]
Hi, I'm relatively new to DDS and have some queries about the usage of cycloneddscxx.

1) Is it possible to configure QoS XML with cycloneddscxx?

2) If yes, is there any examples that I can take a reference to for configuring QoS with XML file?

Appreciate any assistance!

Best Regards,
Kyderio

**Comment by eboasson** [comment]
Hi @Kyderio, thanks for asking, but no, we haven't added the XML QoS specification mechanism yet.

It should be pretty straightforward to add it to the core repository as there is a simple XML parser in `ddsrt` and using it to read a file with QoS settings should be pretty straightforward. However, we're currently tying up the loose ends (like dealing with the few outstanding Coverity issues) before branching off the 0.8.0 release and this is definitely not something we'll get around to in the next few weeks.

If you'd like to contribute it (or enough to make your use case work), we'd be more than happy to accept it but otherwise you'll have to make do without it for now.

**Comment by k0ekk0ek** [comment]
Hi @Kyderio! You're of course welcome to implement QoS configuration through XML (would actually be great), but if you don't mind I'm closing this issue for now. Feel free to link/reopen etc if you'd like to follow-up.

**Comment by hansvanthag** [comment]
I'd say that the standardized DDS QoSProvider API should be worthwhile being considered/supported in the future (like several other DDS implementations do)
