### ISSUE TITLE
Streamer aborts with max bound for bounded strings

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds-cxx#109]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Cyclone version:**
- cyclonedds - master, [779c58](https://github.com/eclipse-cyclonedds/cyclonedds/commit/779c58206d6240a2cc405eece9a66bf70b97cd00)
- cyclonedds-cxx - master, 624da660d9d2c725555bd65bf5ff5c879dbee77b

**Observed result or behaviour:**

When a bounded string with max bound is used the streamer aborts with an exception

**Detailed reproducer**

When using the following IDL file:

```hpp
module msg
{
struct log {
string<255> text_;
};
};
```
The streamer aborts when the bounded string is used with the maximum bound as below:
```cpp
TEST(tooch, bound)
{
  using DDSType = msg::log;
  dds::domain::DomainParticipant dp(0);
  dds::pub::Publisher pub(dp);
  dds::topic::Topic<DDSType> topic(dp, "test");
  dds::pub::DataWriter<DDSType> dw(pub, topic);
  DDSType msg{};
  msg.text_(
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
  dw.write(msg); // => Throws an exception
}
```

This throws an exception as below:

```sh
unknown file: Failure
C++ exception with description "Error Bad Parameter - write failed.
===============================================================================
Context     : void org::eclipse::cyclonedds::pub::AnyDataWriterDelegate::write
Node        : UnknownNode
" thrown in the test body.
```

**Expected result or behaviour:**

The streamer should gracefully handle the bounded strings with the maximum bound

**Comment by sumanth-nirmal** [comment]
Looking at the code we account for the null terminating zero [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/624da660d9d2c725555bd65bf5ff5c879dbee77b/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp#L288), but the bound exceeded check doesnt account this [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/624da660d9d2c725555bd65bf5ff5c879dbee77b/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.hpp#L288), this might be the problem.

**Comment by reicheratwork** [comment]
The exception occurs because the sample is not being written.

The sample passed to write is something completely under the control of the writing side, and it was decided that it was more desirable to not publish data which does not follow the requirements of the data type, than it was to publish it.

There are two ways to solve the write issue:
1. validate the data before writing, skipping samples which do not follow the requirements of the data type
2. put the write inside a try/catch block and do something with the exception

About the null character being included in the bounds check: I am currently working on a unittest and solution for this issue.
