### ISSUE TITLE
C++ standard version?

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#185]
Hello cyclonedds-cxx,

we have some legacy platforms which require the standard c++11.
The generated code from idlc seems to contain std::variant which would require c++17.
I did not found a statement which the lowest support c++ standard version is.

May you could add this information in the README file for more clearance?

**Comment by k0ekk0ek** [comment]
Hi @trittsv, we decided to use C++17 a while back. It's kind-of hidden, but it's in the `CMakeList.txt` for `ddscxx` [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/120c34915a129c1189f6834b967616c248355b8f/src/ddscxx/CMakeLists.txt#L83). I don't recall all the reasons, but I do believe `std::variant` was one of them. `std::optional` (for upcoming X-Types work) being another. However, we could introduce a type mapping that maps onto something similar for older versions(?). If not, perhaps we can make some of those dependencies feature based(?) Anyway, I'm not the worlds foremost C++ expert, but I did remove a bunch of tr/boost mappings for compilers not supporting C++17 yet assuming any projects started now would have at least that. If you know of a way to not require `std::variant`, I'm sure we can help you out.

**Comment by trittsv** [comment]
Thank you @k0ekk0ek for you answer.

the c++17 requirement is one of the reasons which holds use back from replacing opensplice with cyclonedds.
We have to support some limited microcontroller and old projects which need c++11.

A type mapping would be great to be able to switch betweent c++ standards.

I think for a middleware it would be reasonable to support not only the latest c++ standards.
To have some more compatibility resulting in a more brighter usecase.
But i dont know if that fits into your roadmap/design?

**Comment by k0ekk0ek** [comment]
@trittsv, the roadmap can be found [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/ROADMAP.md) and an update to that document is coming soonish. To answer your question, compatibility with older compilers is not high on our priority list as the deletion somewhat demonstrates, but that (of course) doesn't mean we cannot make it happen :slightly_smiling_face:. `std::variant` is used in generated code (a grep of `ddscxx` doesn't show any hits) for unions, and the good news is that you can change which class is used at IDL compile-time by specifying `-funion-template=<something::variant> -funion-getter-template=<getter-method> -funion-include=<filename>`. You can view all options using `idlc -l cxx -h` (or `idlc -l <location-of-idlcxx.so> -h`) by the way. The quickest way to get something working is using [Boost.Variant](https://www.boost.org/doc/libs/1_64_0/doc/html/variant.html) or similar (don't know what you're using for unions now?). That should solve your problems for now.

**Comment by eboasson** [comment]
Hi @trittsv we generally do try to be compatible with somewhat older things because of the domain where the latest available can be quite old. In C++ we figured C++17 made sense specifically because of the way optional fields and unions are mapped in the IDL-to-C++, but apart from that, I think we're still C++11 compatible (it is certainly something we intend to be).

@k0ekk0ek's suggestion of a custom mapping is a way out, but if you don't need optional fields and unions, I think it should be really close to working in C++11 mode already.

**Comment by k0ekk0ek** [comment]
@trittsv, love to hear if my suggestions worked for you.

@eboasson, if that's all that's required I propose we label this issue as a bug and introduce a custom container class for unions that maps onto the C++17 `std::variant` if available or something like `Boost.Variant` if it's not. In the latter case we should then probably add Boost as a dependency in CMake. The advantage of doing it that way would be that `idlc` can map onto a single container class thereby isolating the problem to `ddscxx`.

**Comment by trittsv** [comment]
@k0ekk0ek thanks for your suggestions.

We were able to generate c++11 compatible code and successfully compiled it in our project with cpp standard set to 11.

We added boost as requirement and used the following command:
`idlc -l cxx -funion-template=boost::variant -funion-getter-template=boost::get -funion-include=\"boost/variant.hpp\" common_data_types.idl`

It would be great if this could finds its way into cyclonedds-cxx 🙂

**Comment by eboasson** [comment]
@k0ekk0ek, it sounds like your proposal should do the trick 🙂 @reicheratwork / @e-hndrks, perhaps you would be willing to look into actually doing this, provided you don't have any objections?

**Comment by reicheratwork** [comment]
@eboasson Sure, I will have a look into this addition 👍

**Comment by e-hndrks** [comment]
I would propose we add some compiler flag to indicate you are working with C++11, in which case the compiler switches automatically from using std templates to the corresponding boost templates, without the need to explicitly mention these templates using parameters like -funion_template. That would make things easier for the end user, but would still allow users with newer compilers to just use templates from the std library.
I don't know what such a flag should look like though. An alternative language mapping (-l cxx11 instead of -l cxx) maybe? I am interested to hear other proposals though....

**Comment by trittsv** [comment]
Hey @e-hndrks, I proposed a solution in the linked pull request. May you can have a look.
