### ISSUE TITLE
Symbol "-" not supported as part of the topic name

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-cxx#194]
Hello everyone,
as reported in the title, CycloneDDS-CXX crashes, if I put a "-" in the topic name. In the following, I report my setting.
As message, I used the type:
```idl
struct Float64
{
  double data;
};
```
As "publisher" (which does not publish anything, it just initializes the topic), I used the following:
```c++
#include <iostream>

#include "dds/dds.hpp"
#include "Float64.hpp"

using namespace org::eclipse::cyclonedds;

int main() {
    dds::domain::DomainParticipant participant(0);
    dds::topic::Topic<Float64> topic(participant, "Float64-but-with-forbidden-symbols");
    return 0;
}
```
Running the application, terminates with the following error:
![Publisher - error](https://user-images.githubusercontent.com/79527119/146560466-a1435ef1-46ac-45c5-943f-d73643b7cf8a.PNG)

Attaching a debugger, I could find out, that the topic could not be created:
![Error because of - in topic](https://user-images.githubusercontent.com/79527119/146560698-493a6417-8ccd-4b13-9235-bfb44f0c65ce.PNG)

**Operating system:**
Windows 10

**Cyclone version:**
* cyclonedds: master branch, eclipse-cyclonedds/cyclonedds@717d9d75
* cyclonedds-cxx: master branch, 0453992bacd9f48d08ab0a351cc6c6e7f374d443

Is this part of the standard, and I'm not supposed to use the symbol "-" in my topic name?
Thank you in advance for your help. Any answer would be appreciated.
Best regards,
Ettore Vidotto

**Comment by eboasson** [comment]
I think it depends on whom you ask.

The *only* place in the spec defining what topic names are valid is on the next-to-last page, in an appendix. It is not so much that it defines what is allowed, but that defines what you can use in expressions that need to refer to a topic. So we have taken that as defining what is allowed in topic names, because otherwise you end up with a subset of the functionality simply because you picked an impractical name.

What it says is this:
> TOPICNAME - A topic name is an identifier for a topic, and is defined as any series of characters ‘a’, ..., ‘z’, ‘A’, ..., ‘Z’, ‘0’, ..., ‘9’, ‘-’ but may not start with a digit.

but then it was found that people rather like to use underscores in topic names, and some group of people decided that the spec is in error on this point, that the '-' should have been '\_'. Then ROS 2 came along, translated topic names to match the DDS rules (insofar as they are rules), then decided to ditch the translation because the default implementation at the time had no limitations ... and the end result is that a '/' had to be added. I actually think that allowing a slash is quite sensible giving common naming schemes, but the process to get there was a bit messy.

So what we ended up with is:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/717d9d7504670a20d96f7e74c00fb6ddc7dfc282/src/core/ddsc/src/dds_topic.c#L56-L64

Moreover the names starting with "DCPS" can be read as reserved by the spec, and in Cyclone we decided to forbid applications from creating topics names starting with "DCPS".

So yes, it is the spec, but also not quite ...

**Comment by EttoreVidotto** [comment]
@eboasson Thank you very much for the detailed answer.
