### ISSUE TITLE
deadlock, allocate memory in infinite loop leads to a system freeze of the whole OS

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-cyclonedds/cyclonedds-cxx#201]
When creating a publisher and a subscriber application cyclone deadlocks and grabs memory until the operating system is out of memory. This leads in the best case to an OS intervention and a kill of the application or in the worst case to a system freeze.

The setup looks like the following.
* First application consist of 600 publishers which are publishing 600 different data types on 600 different topics. But not on all topics - only on around 40 - 50 different topics with a rate between 10ms - 50ms.
* Second application has 600 subscribers which are receiving 600 different data types on 600 different topics.

When we start this setup we encounter - always after 11 seconds - a deadlock in the subscriber application. When `htop` is started one can observe that the memory of the subscriber application increases massively until no free memory is left on the system. Now either the application crashes or the OS freezes.

It is impossible to debug the application since this bug crashes the debugger as well. But with linux perf_events I could capture the calls like:
```sh
perf record -F 99 -p PID_OF_SUBSCRIBER -g -- sleep 6000
```

With a tool like flamegraph I discovered that in a thread named "recUC" the function "ddsrt_chh_add_locked" seems to run in an infinite loop. But this is not a real trace since the perf record only shows what function was called and how long in total the process stayed in this function. But here 99% of the runtime was spent in this function so this seems to be involved somehow.

The pseudo code of the subscriber looks like:
```cpp
int main() {
    dds::domain::DomainParticipant m_participant{
        org::eclipse::cyclonedds::domain::default_id()};

    /// In this code generated piece topic1 ... topic600, subscriber1 ...
    /// subscriber600 and reader1 ... reader600 is created.
    /// Every topic, DDSType is unique

    dds::topic::Topic<DDSType1> topic1 =
        dds::topic::Topic<DDSType1>(m_participant, topicName1.c_str());
    dds::sub::Subscriber subscriber1 = dds::sub::Subscriber(m_participant);
    auto qos = subscriber1->default_datareader_qos();
    qos << dds::core::policy::History::KeepLast(10);
    dds::sub::DataReader<DDSType> reader1 =
        dds::sub::DataReader<DDSType>(subscriber1, topic1, qos);

    /// ... remaining objects are created in the same manner

    // main loop
    while (true) {
        dds::sub::LoanedSamples<DDSType1> samples = reader1->take();
        if (samples.length() > 0) {
            for (auto& sample : samples) {
                if (sample.info().valid()) {
                    std::cout << "sample received on " << topicName1.c_str()
                              << std::endl;
                }
            }
        }

        //... the remaining reader2 ... reader600 are handled in the same
        // fashion for DDSType2 ... DDSType600
    }
}
```

The publisher has the same quality of service and is also created pretty straight forward. But I omitted the code here since it is not the application that crashes.

**Comment by eboasson** [comment]
Hi @elfenpiff, I have a suspicion what it might be even though I have not actually managed to reproduce it. I did make a program that I suspect is pretty similar and in the internals I do see symptoms close enough to those you describe to have some faith in my suspicion.

Would you be willing to give this: https://github.com/eboasson/cyclonedds-cxx/tree/thousand-topics a try? There are two commits in there:
* One with my attempt at reproducing it and I'd be interested if you could tell me how well it matches what you were doing;
* One with a (provisional) fix. It completely fixes it for me, but I consider it provisional because I would prefer a better mixing function than a simple `xor` and I need to ponder how to do incorporate that in the rest of the code.

**Comment by sumanth-nirmal** [comment]
@eboasson I ran into this issue with another similar setup. The call trace when this is happening is as below

![image](https://user-images.githubusercontent.com/13644774/154388325-b3f48e71-f0a4-45cf-a5ad-691a645e763c.png)

I did debug this a little and realized that it got stuck in the add -> resize -> add loop here https://github.com/eclipse-cyclonedds/cyclonedds/blob/426304f97645572c62d47bbd9558e72a4ff7b74f/src/ddsrt/src/hopscotch.c#L216 eventually causing the memory to exhaust.

From the code, it looks like that the resize() is called recursively with `ddsrt_hh_add()` and I am not sure if this is a limitation of the hopscotch algorithm itself?

Also if the topic doesn't have any keys then do we still need to compute these hashes?

---

I also did try the change (hash computation to include the serdata hash) from https://github.com/eboasson/cyclonedds-cxx/tree/thousand-topics and it solves the problem of rouge memory allocation.

It will be difficult to get the reproducer I have because of the dependencies, but I will try to adapt your test to replicate the scenario I have that causes this error.

**Comment by eboasson** [comment]
Thanks @sumanth-nirmal ! That completely fits my own analysis and I am glad you confirm that my commit indeed fixes the issue. I am not all that worried about not having a reproducer, although do find it uncomfortable that I don't understand why it happens around 600 topics (really types!) for you.

I can accept that ballooning memory use may have slowed it down on my laptop: I do believe it touches all the memory it allocates, so it will soon start swapping and I quite possibly didn't wait long enough. On a machine that doesn't swap (or has a very limited amount of swap space available) I am sure the outcome would be different.

As to your questions:

> I am not sure if this is a limitation of the hopscotch algorithm itself?

It is. It can only handle a limited number of hash collisions for a single bucket — something the literature left as an exercise for the reader 🤓. Statistically, it should be ok as long as the hash functions are good because getting scores of different key values mapping to the same hash *and* being inserted in the table at the same time is unlikely, but I have never been one for gambling ...

The reason it blows up in this case is that this particular hash table uses the following equality test:
https://github.com/eclipse-cyclonedds/cyclonedds/blob/426304f97645572c62d47bbd9558e72a4ff7b74f/src/core/ddsi/src/ddsi_tkmap.c#L79-L82
If, like in the C++ binding right now, the hash is the same but the function pointer isn't, there is trouble on the horizon. Including the function pointer in the hash solves that, and that's what `serdata_basehash` effectively does (though it isn't *quite* as good as using it as an IV for the hash function).

(In C it is all dynamic and so there you end up with a single entry shared by all keyless topics.)

> Also if the topic doesn't have any keys then do we still need to compute these hashes?

Yes and no. They could be eliminated completely but it would break the pattern. I never figured the upside would be big enough to overcome that downside, but I do have to admit that I was wrong in my expectation that most topics have key fields. Perhaps that shifts the balance.

The C++ code is templated, resulting in each type having its own equality test. I think it would be easy enough for keyless topics to use the same function (you'd still need to be diligent and mix in `serdata_basehash`, although that currently includes more than just the equality test and so needs a bit of investigation as well). At the very least that would speed things up a bit. If everything comes together properly, it will also reduce memory usage, &c. I need a hand from @reicheratwork to sort that out, though.

And ideally, the compare function would be specialised to the type of the key rather than to the type of the sample, but that seems a more complicated to me than doing it only for keyless topics.
