### ISSUE TITLE
safe_enum class not genererated with idlcxx

### ISSUE THREAD

**Issue by NoeSechet** [eclipse-cyclonedds/cyclonedds-cxx#209]
I create some code using the idlcxx generator. In that code I define an enumeration like so: 

![image](https://user-images.githubusercontent.com/44672601/152325973-af10e306-33ef-4b10-880c-437c53bfeeb3.png)

On the generated class from that enum, I would like to use the **underlying()** function (like below), which is a member of the **safe_enum** class.

![image](https://user-images.githubusercontent.com/44672601/152327622-59b62e6b-bbe0-43ed-b14b-5267023bc9f5.png)

However, the generated code doesn't create a **safe_enum**, but a normal **enum class**: 

![image](https://user-images.githubusercontent.com/44672601/152324610-1669c9d7-d8d4-473f-bea6-64d3a8b4d7bd.png)
(above is generated code for that enum, no sign of the **safe_enum** class anywhere is the generated code)

Because of that, we get that error: 

```
error: request for member ‘underlying’ in ‘reply_header.{namespace}::ReplyHeader::remoteEx()’, which is of non-class type ‘{namespace}::RemoteExceptionCode_t’
             ::std::to_string(reply_header.remoteEx().underlying()),
                                                      ^~~~~~~~~~
```

Is there another way to generate a **safe_enum** via an IDL file? Or is that feature not yet present with Cyclone?

**Comment by reicheratwork** [comment]
Hi @NoeSechet, I think this is caused by conflating two things with eachother: the DDS API safe_enum wrapper and the C++ language binding mapping of IDL enums.

1. the safe_enum class is a wrapper for enums in C++ DDS API to allow for "safe" enums, for compilers which did not yet support enum classes (so before C++11)
2. the `underlying()` function is there access the underlying container type which is the "internal" representation, since the safe_enum is there to not allow free conversion between integer types and the enum
3. whereas the v1.4 C++ language binding explicitly says that an IDL enum is to be mapped onto an enum class (_section 6.9_), so the C++11 built-in functionality of a safe enum implementation
4. the enum class does not have an `underlying()` function to convert to the underlying integer representation of the instance, as this is a C++ DDS API thing, not a C++ language binding thing

The enum class is there to prevent implicitly converting between integers and itself.
The easiest way to get an integer representation is to use an explicit C cast:
```
RemoteExceptionCode_t code = RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT;
auto str = std::to_string((int)code);
```
, or a C++ static_cast:
```
RemoteExceptionCode_t code = RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT;
auto str = std::to_string(static_cast<int>(code));
```

In both cases, you should have `str` containing `"2"`.

I'd personally prefer using the C++ `static_cast` approach, as old-style C casts cause some compilers to give warnings.

**Comment by NoeSechet** [comment]
Hi @reicheratwork,

thank you for your answer! It makes a lot of sense now. We thought the safe_enum class was the latest thing to used. But after updating our other DDS library we figured that the "safe_enum" wasn't created either in the IDL generated code. 

We were doing the static_cast solution until finding a way to use "underlying()" but it turns out it's already the correct method

I am closing this issue.

Thank you again
