### ISSUE TITLE
Setting DomainParticipantQOS (liveliness, detection_period...)

### ISSUE THREAD

**Issue by NoeSechet** [eclipse-cyclonedds/cyclonedds-cxx#211]
We wanted to set QOS on a participant, but we couldn't find how to do it with Cyclone. 

How would you go about setting the **liveliness_lease_duration** with the **dds::domain::qos::DomainParticipantQOS** class using Cyclone? 

In our application we would like to know when a subscriber shuts off as soon as possible.

Thank you for your work

**Comment by eboasson** [comment]
That's because it doesn't allow you to configure that setting via the QoS. This is in line with the specs as neither the DCPS spec nor the C++ API spec have a way of configuring a lease duration for the DomainParticipant, but of course it ultimately needs to be configurable. With all the work that has been done in Cyclone, adding a non-scary-sounding way of doing this was forgotten, and so all that is available right now is an `Internal/LeaseDuration` setting in the XML configuration.

I'll do a PR that moves it to the less-scary `Domain/LeaseDuration` (the `Internal` one will then still work but with a warning) to set a default, and add it to the participant QoS to make it easy to overrule it per participant.

**Comment by NoeSechet** [comment]
Thank you for your quick answer as always @eboasson,

Then I will use the XML configuration for now, looking forward to having the feature available in code.

I will close this issue.

Thank you again
