### ISSUE TITLE
Error when building CycloneDDS-CXX 0.9.0 on Windows with Visual Studio 15 2017

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-cxx#260]
Hello everyone,
as reported in the title, I cannot build CycloneDDS-CXX 0.9.0 using Visual Studio 15 2017, since the following errors occur:
![CycloneDDS-CXX error](https://user-images.githubusercontent.com/79527119/162196633-21ba167b-6348-463f-b253-1f4b86309641.PNG)

This happens when building CycloneDDS and CycloneDDS-CXX in the current master branches or with the newly released 0.9.0 version.

**Operating system**
Windows 10

**Used CMake generator**
Visual Studio 15 2017 Win64

**Commands to install CycloneDDS**
```bat
git clone https://github.com/eclipse-cyclonedds/cyclonedds --branch releases/0.9.x
cd cyclonedds
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=D:\Project\TestCycloneDDS\InstallationC ..
cmake --build . --target install
```
**Commands to install CycloneDDS-CXX**
```bat
git clone https://github.com/eclipse-cyclonedds/cyclonedds-cxx --branch releases/0.9.x
cd cyclonedds-cxx
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=D:\Project\TestCycloneDDS\InstallationCXX -DCMAKE_PREFIX_PATH="D:\Project\TestCycloneDDS\InstallationC" ..
cmake --build . --target install
```
What would be necessary to change in order to compile CycloneDDS-CXX with Visual Studio 2017?
Thank you in advance for your help. Any answer would be appreciated.
Best regards,
Ettore Vidotto

**Comment by reicheratwork** [comment]
Hello Ettore,

I am looking in to this issue.
I should have some more information soon.

Regards,
Martijn Reicher.

**Comment by reicheratwork** [comment]
Hello Ettore,

I have looked into this issue, and there seem to be two things going on here:
- the first is that for some reason, MSVC15 seems to be more picky and requires the <algorithm> include to get the std::min and similar functions, whereas later versions get it through other means, this is causing the issues in the cdr_stream.cpp file, adding this to the beginning of cdr_stream.cpp fixes this issue
- the second is that MSVC15 seems to have problems with the std::enable_if template functions for conditional compilation, while this should be detected and fixed by the Missing.hpp file, this does not look it is happening correctly, which is causing the issue in the datatopic.hpp file

I am examining the second issue further, and i will create a PR including a fix referencing this issue, but if you have no fundamental reasons for using MSVC15, maybe you can try using MSVC17 in the meantime, as i experience no issues when using this version.

Regards,
Martijn Reicher.

**Comment by reicheratwork** [comment]
Hi Ettore,

If you could give my solution `https://github.com/reicheratwork/cyclonedds-cxx/commit/c9fa3c72e1654103a52c63a5298ff70670931951` a try, and see if it fixes the issue?

Regards,
Martijn Reicher.
