### ISSUE TITLE
Use xtypes with CycloneDDS-CXX

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-cxx#272]
Hi everyone,
I have a quick question. With CycloneDDS 0.9.0, the XTypes support has been included, with the caveats you reported [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/dev/xtypes_relnotes.md).
In particular, the types `dds::core::xtypes::DynamicType` and `dds::core::xtypes::DynamicData` are not supported. Is there any plan of including them for the CXX-bindings in the future?
Thank you very much in advance.
Bests,
Ettore Vidotto

**Comment by eboasson** [comment]
Hi @EttoreVidotto we've decided to wait and see what the interest is for the dynamic API. Doing anything dynamically typed is dramatically more pleasant in Python (where it works today and you don't have treat dynamic data as anything special), but we can think of a couple of situations where going via Python isn't feasible. We're open to doing it if it really opens up doors for Cyclone that otherwise would remain closed.

I should perhaps point out that there is a difference to "us" doing it, and "us" accepting contributions for it. We may not be keen on actually doing it, but contributions implementing it would be gratefully accepted!
