### ISSUE TITLE
zero copy API

### ISSUE THREAD

**Issue by nate800** [eclipse-cyclonedds/cyclonedds-cxx#283]
There does not seem to be a way to create a read condition when using iceoryx.  Looks like this is on the TODO list.  

What is the intention for the zero-copy API?  Will the application code require significant modification depending on whether or not zero-copy is enabled?

https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/fdbef1f77433cdac9957ab3001f50af6ef42b08e/src/ddscxx/CMakeLists.txt#L98

**Comment by eboasson** [comment]
> There does not seem to be a way to create a read condition when using iceoryx. Looks like this is on the TODO list.

That's not on the TODO list, that should just work.

All the data that arrives is inserted in the appropriate reader history caches (RHC), and so that includes data arriving via Iceoryx. The RHC is the bit that implements the read conditions, and so I find your observation that those don't work when using Iceoryx quite surprising.

The line you quote with the TODO is has to do with which shared library depends on which other shared library. We really want to encapsulate Iceoryx so that there is only one place where you find a dependency (the Cyclone DDS core), but currently, the shared library implementation the C++ API needs to link with Iceoryx directly for some implementation details. It doesn't surface at the API.

> What is the intention for the zero-copy API? Will the application code require significant modification depending on whether or not zero-copy is enabled?

Depends on what you consider "significant" I suppose. You always have to make *some* modification to your code, because the ownership of the memory changes. The standard interface copies the data, and so after calling `write`, you can do as you please with the memory, and what you get out of `read` or `take` is yours to use/modify/do whatever.

For zero-copy operation, the middleware needs to own the memory, and when you want to `write` data, you have to first borrow some memory from the middleware in which you construct your sample and then you "return it" by calling `write`. Once you write it, you mustn't touch it anymore. Similarly, when you `read` or `take` data via the zero-copy interface, you get a pointer to shared memory that remains valid until you "return" it. But you must not ever modify that memory.

That may require significant changes to application code.

Separate from that, zero-copy is only supported for "simple" types (scalars, arrays and structs, basically, because pretty much everything else involves pointers and those don't play well with zero copy). So again, if your application already uses such types, it is a non-issue; but if it uses complicated types that aren't compatible with zero-copy operation, you may need to make significant changes.

**Comment by nate800** [comment]
The read condition in the test code uses the traditional reader as an argument in the read condition.
https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/fdbef1f77433cdac9957ab3001f50af6ef42b08e/src/ddscxx/tests/SharedMemory.cpp#L229

I do not have a traditional reader available, only the iceoryx subscriber.  

`iox::cxx::optional<iox::popo::Subscriber<LargeData_T, iceoryx_header_t>> large_data_reader`

At the moment, I poll to see if data is available.

`large_data_reader->hasData()`

if I pass large_data_reader into a read condition : 

`dds::sub::cond::ReadCondition(large_data_reader, dds::sub::status::SampleState::not_read(), some_functor)`

The compiler complains that methods `is_nil` and `delegate` are not available.  I suppose it needs to be of type `dds::sub::AnyDataReader`.

Given the test code has a function :

`void CheckData( const bool must_use_iceoryx, const dds::sub::LoanedSamples<T> & samples, const T & test_data)`

I thought maybe the intention was might be for both zero-copy and the traditional API to co-exist.  I was planning to use an #ifdef to enable/disable zero-copy in the application code.

**Comment by eboasson** [comment]
Ah! I see! Yes, that won't work.

The thing about the Cyclone DDS–Iceoryx integration is that it happens "under the hood": if you enable the shared memory support (1) and you create a DDS DataReader (2), then Cyclone will automatically also create an Iceoryx subscriber and similarly for DataWriters/publishers.

Of course you're welcome to (also) create Iceoryx publisher/subscribers directly in the application, but those don't integrate nicely with the DDS operations — perhaps there'd be a way to make that possible, but that's not on the radar right now. What you can still do in that case is use Iceoryx' native mechanisms, something like [this](https://iceoryx.io/v2.0.1/examples/waitset/) on their really nice website. (Too many people involved to thank them here, but hopefully some will see this 🙂)

(1) i.e., SharedMemory/Enable = true
(2) it must meet some constraints on the QoS, nothing onerous

**Comment by nate800** [comment]
Using the DDS interface for the writer seems to take this approach. 
`
if (writer.delegate()->is_loan_supported()) { 
  auto & loaned_sample = writer.delegate()->loan_sample();
  make_sample_(loaned_sample, i);
  writer.write(loaned_sample);
};  
`
The most analogous approach for the reader seems to be the following : 
`auto large_data_reader = std::make_shared<dds::sub::DataReader<LargeDatraType>>(sub, top);
large_data_reader->delegate()->loaned_take(...)
`

The `loaned_take(...)` function does not seem to be part of the standard API, or part of the FastDDS or connext implementations.  I just wanted to clarify what I am "supposed to do" when using cyclonedds-cxx.  I'm perfectly fine using the iceoryx API directly, as shown in the test code.

**Comment by eboasson** [comment]
In

> ```
> if (writer.delegate()->is_loan_supported()) { 
> ```

you can just write `writer->is_loan_supported()`, the OMG decided to use the `.` operator for accessing standardised operations, and to allow accessing vendor extensions via the `->` one. The delegates are the implementation-specific things and contain a lot of implementation details and so you generally don't want to invoke things in the delegate directly if there is some way of accessing it via the standard interfaces. Cyclone has a "clean" version for taking loaned samples from a DataReader:

```C++
template <typename T>
dds::sub::LoanedSamples<T>
dds::sub::detail::DataReader<T>::take()
```
(and some variants) for which the implementation calls `loaned_take`, but the idea is that you don't need the `loaned_take` operation in your code. E.g.:
```C++
            dds::sub::LoanedSamples<msgType> samples;
            samples = reader.take();
            if (samples.length() > 0) {
                dds::sub::LoanedSamples<msgType>::const_iterator sample_iter;
                for (sample_iter = samples.begin();
                     sample_iter < samples.end();
                     ++sample_iter) {
                    const msgType & msg = sample_iter->data();
                    const dds::sub::SampleInfo& info = sample_iter->info();
```
does the trick.

There should be a proper example for this ...

**Comment by nate800** [comment]
Thanks.  Looking forward to version 1.0.
