### ISSUE TITLE
the helloworld example raises an exception on domain participant creation 

### ISSUE THREAD

**Issue by RamziKaroui** [eclipse-cyclonedds/cyclonedds-cxx#284]
When running the CXX example on windows x64 (VS2017) , the ddscxxHelloworldPublisher (as well as the subscriber app ) raises an exception 

> ddscxxHelloworldPublisher.exe

== [Publisher] Exception: When explicitly provide a config, a specific domain id has to be provided as well.

Context     : __cdecl org::eclipse::cyclonedds::domain::DomainParticipantDelegate::DomainParticipantDelegate
Node        : UnknownNode

> ddscxxHelloworldSubscriber.exe

 ==[Subscriber] DDS exception: When explicitly provide a config, a specific domain id has to be provided as well.

Context     : __cdecl org::eclipse::cyclonedds::domain::DomainParticipantDelegate::DomainParticipantDelegate
Node        : UnknownNode

Note: %CYCLONEDDS_URI% was empty during the execution of the programs

**Comment by reicheratwork** [comment]
Hi @RamziKaroui , I will have a look at this today.

**Comment by RamziKaroui** [comment]
The issue is not linked to Cyclone Core implementation . The issue can be closed.

**Comment by millma** [comment]
For anyone that runs into this error, the issue for me was due to the Cyclone DDS* DLLs being build with `CMAKE_BUILD_TYPE` set to RelWithDebInfo while my application build was configured with Debug.

In particular, the exception is thrown when the `DomainParticipantDelegate` constructor in ddscxx.dll is called and the `std::string config` parameter is mangled (invalid size and garbage contents), resulting in the exception being thrown since it appears an explicit config is being provided with the default domain ID even though the TDomainParticipant constructor is calling with an empty string object.
