### ISSUE TITLE
v0.10.1 wrong version number in cmake

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#309]
Hey i just wondered why in cmake the version is set to `0.10.0` and not `0.10.1`.
Or is there any special meaning?

https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/a552242032f297ffc28ef5a0ad48c578b18bff4a/CMakeLists.txt#L13

**Comment by eboasson** [comment]
@trittsv thank you for pointing that out, we screwed up somewhere along the several manual steps in getting some properly tagged as a new (minor) release. And that the one time we looked at each other and decided that the "release candidate" business is such a useless hassle because you really sit there wondering how long you have to wait ...

I just pushed 0.10.2rc1 ... all version numbers in the three repositories have been updated, branch created, etc. Should be good now.

**Comment by trittsv** [comment]
its fixed in cyclonedds-cxx 0.10.2. Because of that i will close this issue.
