### ISSUE TITLE
OpenSplice leftovers

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#347]
Hey there are some OpenSplice leftovers in the code like here:

https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/0955aa0ea087e2cf11424448df5d2e6c17bd976b/src/ddscxx/include/dds/sub/TDataReader.hpp#L1616

Can they be removed or the name replaced with cyclonedds?
(Im open to do that if desired)

**Comment by eboasson** [comment]
Those references should all go, I'd say. OpenSplice has been a most generous donor to Cyclone but there's no value in retaining such references. This particular one can be removed, I haven't checked all of the others, though.

If you are happy to help with removing them and/or rewriting them so that they add something of value, that'd be really wonderful!

**Comment by trittsv** [comment]
Hey @eboasson, in the PR #356 i rewrote the remaining vortex opensplice texts, may you can have a look 😃
