### ISSUE TITLE
Not support OMG IDL standard forward declaration for class

### ISSUE THREAD

**Issue by michaelchao** [eclipse-cyclonedds/cyclonedds-cxx#371]
*OMG IDL* support syntax: forward declaration for class
```
struct A;
struct B { A a_;};
struct A {string name_;};
```
however cyclonedds-cxx not support handle this case.
The root cause is that member whose data type is class in parent class is declared as object, not pointer. This way need class of member data type must be defined before parent calss. So following case can not be handled:
```
struct A;
struct B;
struct B { A a_;};
struct A {B b_;};
```

**Comment by eboasson** [comment]
I think you're mistaken in what the forward declarations in IDL allow. If you look at [OMG IDL4.2](https://www.omg.org/spec/IDL/4.2/PDF), section 7.4.1.4.4.4.4 "Constructed Recursive Types and Forward Declarations", it says:

> An incomplete type can only appear as the element type of a sequence definition. A sequence with incomplete element type is termed an incomplete sequence type.

So it correctly rejects your `struct B` definition. The error message would be much better if it pointed out that type `A` cannot be used at that point because it is incomplete, instead of simply saying "unknown".

**Comment by michaelchao** [comment]
> 

For fastdds, following case is supported by its fastddsgen tool:
```
struct A;
struct B { A a_;};
struct A {string name_;};
```
Howerer, cyclonedds idlc does not, I am a little confused, is this case a normal case or bad case?

**Comment by eboasson** [comment]
That example is not valid OMG IDL.

If you study the history of (OMG) IDL and the limitations it imposes, you'll find that it is something like a subset of C with some template types (`string` and `sequence`) and a few weird additional rules so it fits with C, C++, Ada, ... Java is already a bit too new to have been taken into account, and it shows.

In practice, any construct that doesn't map easily to all of these languages is forbidden — and as this particular example is also illegal in C/C++, it is a surprise that fastddsgen accepts it.

**Comment by michaelchao** [comment]
Deep in source code of fastddsgen and idlc, I find the root case why support capability if them is different.
for fastddsgen, it will emit:
```c++
class A;
class B {
public:
    ...
    A * m_a;
    ....
};
class A {
};
```

Howerver, idlc will emit:
```c++
class A;
class B {
public:
    ...
    A  m_a;
    ....
};
class A {
};
```

You will see, member type of A is object in idlc's output, but member type of A is object pointer in fastddsgen's output.
There is no way to support **class forward declaration** in idlc's output, I guess this could be one reason why cyclonedds not support what I issued.

**Comment by eboasson** [comment]
`A * m_a` is a, let's say, *very creative* interpretation of the two IDL-to-C++ mappings (the "classic" and the "modern") one! 😂

**Comment by dpotman** [comment]
There are a few problems related to this issue: 
1) IDLC does not detect incorrect incomplete type usage, this is fixed in the linked [PR](https://github.com/eclipse-cyclonedds/cyclonedds/pull/1593)
2) A struct or union member can only use an incomplete type in a sequence (as mentioned above) or as an external member (using the `@external` annotation), except for an external array of incomplete types. 
3) The type meta-data generation in IDLC had a bug related to handling forward declarations. This is also fixed in the [PR](https://github.com/eclipse-cyclonedds/cyclonedds/pull/1593). This bug caused the error message (the 'Type id not found for type ..' message)
4) The IDLC C++ code generator does not (correctly) output forward declarations, so even in case of correct use of a forward declared type, the generated code will not compile. I'll look into this issue.

**Comment by michaelchao** [comment]
The answer seems has been found, this issue should be resolved, thank you every one :)
