### ISSUE TITLE
Noob Question: How should I track multiple DataWriter objects through a map or a vector?

### ISSUE THREAD

**Issue by adam-lee** [eclipse-cyclonedds/cyclonedds-cxx#394]
I have DataWriter dealing with different data types (meaning each DataWriter's type is different).
Surely there is a way of putting these into a std::map, but I haven't yet figured it out.

If this is the right approach, can someone please share a short example?
If this is the wrong approach, point me to the right direction?

**Comment by eboasson** [comment]
That's not an easy question for me to answer. I would say that this[^1] ought to work, but that would imply equality (or perhaps ordering) is undefined for them, or that some hash functions are missing. You're way into C++ details there, while I rather prefer C and Haskell ... @e-hndrks @reicheratwork am I barking up the right tree here?

[^1]: a `std::map<T,DataWriter<T>>` in my understanding of what you're saying

**Comment by adam-lee** [comment]
Yes that's about exactly what I tried, but I couldn't come up with a way to add a map as a class member:

```
awesome_interface.hpp:62:53: error: use of undeclared identifier 'T' 
std::map<int, dds::pub::DataWriter<T> > writers_;
```

How does everyone generally keep track of entities like writers? Perhaps I'm thinking it wrong?

**Comment by reicheratwork** [comment]
@adam-lee , interesting problem, let me think about this for a little while

**Comment by reicheratwork** [comment]
@adam-lee , had a quick look at your issue, and the problem is that what you want to do, like this:
`std::map<int,dds::pub::DataWriter<T>>`
is not allowed in C++, because both the key type and the mapped type in the `std::map` need to be a single type, and `DataWriter<A>` and `DataWriter<B>` are not the same type in C++'s eyes.

What you can do, because you know all classes that you want to use at compile time, is use a combination of a traits/singleton approach. Make a template class, whose template parameter is the datatype you want to use, and then have a singleton container of some sort, with the Readers/Writers/Topics etc contained within it.

I have made a small example on [this branch](https://github.com/reicheratwork/cyclonedds-cxx/tree/type_mapping_example) on my personal repo, to show my approach.
Check the file `examples/helloworld/Traits_Approach.hpp` for the "secret sauce".

**Comment by adam-lee** [comment]
@reicheratwork I'm giving this a try. I will report back ASAP. Ty!

**Comment by adam-lee** [comment]
@reicheratwork Took a look and I think your "secret suace" is the way. 

Much appreciated! Gonna ask my boss to make a donation to the Eclipse foundation 👍 .
