### ISSUE TITLE
Question about logic when reading the CDR header

### ISSUE THREAD

**Issue by NickFoubert** [eclipse-cyclonedds/cyclonedds-cxx#415]
I'm working on another language binding to Cyclone and I'm scratching my head about this:

https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/e57ef9e99e781d93998d38d40709a660aa33442e/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp#L212-L216

is the logic backwards or am I misunderstanding something?

**Comment by eboasson** [comment]
You now have me scratching my head as well. IINM for the particular case of `@final` topics, XCDR1 is a strict extension of basic CDR (a.k.a. pre-XTypes CDR). The XTypes "data representation" setting doesn't even have a separate "basic CDR" setting:

> 7.3.1.2.1.15 Constrained Data Representations
>
> The IDL definition of the @data_representation annotation is:
> ```
> // Positions are defined to match the values of the DataRepresentationId_t
> // XCDR_DATA_REPRESENTATION, > XML_DATA_REPRESENTATION, and
> // XCDR2_DATA_REPRESENTATION
> @bit_bound(32)
> bitmask DataRepresentationMask {
>   @position(0) XCDR1,
>   @position(1) XML,
>   @posiiton(2) XCDR2
> }
> ```

Looking at the change that introduced this:

```
commit 4a7f350532a0ca4a623ce3c3cc56f85def9e4da1
Author: Martijn Reicher <martijn.reicher@zettascale.tech>
Date:   Mon Feb 21 09:52:11 2022 +0100

    Add setting of allowed encodings through datarepresentation annotation
    
    Signed-off-by: Martijn Reicher <martijn.reicher@zettascale.tech>

diff --git a/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp b/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
index c19439de..351cb4d1 100644
--- a/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
+++ b/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp
@@ -196,7 +196,7 @@ bool read_header(const void *buffer, encoding_version &ver, endianness &end)
     case extensibility::ext_final:
       switch (field) {
         case PLAIN_CDR:
-          if (TopicTraits<T>::minXCDRVersion() == encoding_version::basic_cdr)
+          if (TopicTraits<T>::allowableEncodings() & DDS_DATA_REPRESENTATION_FLAG_XCDR1)
             ver = encoding_version::basic_cdr;
           else
             ver = encoding_version::xcdr_v1;
```

I think the issue is that the `minXCDRVersion` to `allowedEncodings` caused the old logic to become impossible and this fact slipping through the cracks.

I suspect the check is actually not needed at all and that setting `ver` always to `xcdr_v1` would be correct. But this is XTypes and so I am bound to get it wrong somehow 😵‍💫

@reicheratwork what do you think?

**Comment by reicheratwork** [comment]
Looking at that piece of code, it gets invoked when deserialized a cdr-encoded chunk of data. This is the part that determines which decoding scheme to use, based upon the datatype's properties and the information received through the CDR header.

So what's happening is that first the endianness is determined, and that bit is discarded, just leaving the cdr encoding information for further switching:
`auto field = *ptr & ~BO_LITTLE;`

Next, we look at the extensibility of the main datatype `TopicTraits<T>::getExtensibility()` and switch to different cases based on that.
Now for the `appendable` and `mutable` extensibilities, the choice for encoding scheme is unambiguous, since only XTypes serialization can represent this datatype. But in the case of `final` datatypes, combined with the `PLAIN_CDR` encoding flag, this can either mean:
- legacy cdr encoding
- `PLAIN_CDR` xcdr_v1 encoding (deprecated)

And this might cause issues, since these support different features, e.g.: if you have a final struct data type, but it contains an appendable enumerator, or a member which is an appendable struct, this is encoded as `PLAIN_CDR`, but if you try to deserialize this with a legacy (or `basic_cdr_stream`) deserializer, this may cause all sorts of "interesting" errors.

This is why it looks at the `allowableEncodings()` topic trait: this encodes which types of encoding are supported for a datatype. If some properties requiring XTypes functionality are encountered (like `appendable`/`mutable` types, `optional` members, etc.) the `IDL_DATAREPRESENTATION_FLAG_XCDR1` flag is unset in the trait, as the CycloneDDS serialization only wants to write `xcdr_v2`. So the way you should read the part you are confused about is more like the following:
"If you want to deserialize a final type, and the cdr encoding flag says it is encoded as plain CDR, you might be receiving either a legacy CDR or a deprecated XTypes (v1) message. Therefore you want to look at the data type itself and see whether you are actually dealing with nothing related to xtypes, or that there might be xtypes related stuff inside the so-called final datatype, and deserialize accordingly."

At least, this is why I implemented it this way.
I am as always open to suggestions/improvements.

**Comment by reicheratwork** [comment]
@NickFoubert , maybe have a look at PR #419 ?
