### ISSUE TITLE
[Question] return_loan API

### ISSUE THREAD

**Issue by showmethejinw** [eclipse-cyclonedds/cyclonedds-cxx#437]
When I checked, the return_loan method does not exist in DataReader.
How can I utilize the functionality in cyclone DDS?
Thank you in advance.

**Comment by eboasson** [comment]
Do you mean `dds_return_loan` in the C API (I am asking because of my response on #435) or are you looking for the equivalent in the C++ API?

If the former, then you are probably missing `#include "dds/dds.h"`.

If the latter, the C++ API takes care of returning loans in the destructor of the `LoanedSamples` type, so you don't need to explicit return them.

**Comment by showmethejinw** [comment]
@eboasson, Thank you for your kind reply!
