### ISSUE TITLE
[Question] register_type API

### ISSUE THREAD

**Issue by showmethejinw** [eclipse-cyclonedds/cyclonedds-cxx#438]
When I checked, the return_loan method does not exist in cyclone DDS
How can I utilize the functionality in cyclone DDS?
Thank you in advance.

**Comment by eboasson** [comment]
Surely there must be a typo in comment, given #437 and the title of this issue 🙂

There are two sets of APIs for DDS from the OMG: the "classic" ones, which are the result of taking an IDL file defined in the spec and applying the IDL-to-_X_ language mapping to it. That yields the "classic" C, C++, Java, ... APIs. Cyclone doesn't support those, they are all a pain to use. (Typed C++ interfaces with code generation instead of relying on templates in 2023? Really?)

For C++ (and Java) a "modern" API has been spec'd as well. That by now is pretty old, but it is essentially based on the C++11 feature set. Cyclone's implementation still supports C++11, but for various application types it makes sense to use C++14 or C++17 instead, for example for the mapping of unions.

In these new APIs, there's no longer a need for "register_type". It is all handled via type traits.

**Comment by showmethejinw** [comment]
@eboasson, Thank you for your kind reply.
Your answers are very helpful. 
Thank you for not only asking the question, but also explaining the background information.
Have a nice day 😄
