### ISSUE TITLE
Question about each default QoS value

### ISSUE THREAD

**Issue by showmethejinw** [eclipse-cyclonedds/cyclonedds-cxx#446]
Hello,

I am trying to test communication between ROS2 HelloWorld example and native DDS application.
So, first, I need to apply the native DDS application as the QoS value of the ROS2 sample application.

I can set the value as the QoS value of the ROS2 sample application. 

But I just want to know the each default QoS value.
Is there any document that lists each default QoS value?

Thank you in advance.

**Comment by eboasson** [comment]
Hi @showmethejinw, I always simply look in the [DDS specification](https://www.omg.org/spec/DDS/1.4/PDF) section 2.2.3: there is a big table with all the standardized QoS settings and the defaults.

You might want to check out `cyclonedds ls --qos` (you get it with the Cyclone python binding), that shows you all details of all readers/writers. And finally, pay careful attention to the names of the topics and types: ROS 2 mangles them a bit by default, so that the topic names begin with "rt/" and the type names have "dds_" somewhere in the name (see, e.g., https://github.com/eclipse-cyclonedds/cyclonedds/issues/1766)

**Comment by showmethejinw** [comment]
@eboasson, Thank you for your kind and quick reply.

Thanks to you, I was able to verify native DDS application and ROS2 DDS Application communication.

When I check the topic in ROS2, dds_ is missing from the type.
When adding the dds_ namespace in IDL, where exactly should I add it?
(you told me somewhere in the name.)

```shell
$ ros2 topic info /chatter --verbose
Type: std_msgs/msg/String

Publisher count: 0

Subscription count: 1

Node name: listener
Node namespace: /
Topic type: std_msgs/msg/String

``` 

ROS2 topic infomation told me
the topic name is "/chatter"
the type name is "std_msgs/msg/String"

But the actual topic name "rt/chatter" and type name is "std_msgs/msg/dds_/String_"

the topic names begin with "rt/" is OK.
In case of type name, how can I know the exact type name?
I just have to check IDL or generated source code?

If I generate the idl file below, the code is normally generated, but if I change "struct String_" to "struct String", the following error message occurs.
"cyclonedds-cxx/examples/helloworld/HelloWorldData.idl:16:20: syntax error"
Why did the syntax error occur?

```
module std_msgs {
    module msg {
        module dds_ {
            struct String_ {
                string data;
            };
        };
    };
};
``` 

Thank you in advance.

**Comment by eboasson** [comment]
> @eboasson, Thank you for your kind and quick reply.
> 
> Thanks to you, I was able to verify native DDS application and ROS2 DDS Application communication.

Great!

> When I check the topic in ROS2, dds_ is missing from the type. When adding the dds_ namespace in IDL, where exactly should I add it? (you told me somewhere in the name.)

ROS treats the names as a name space + a message type name and adds the `dds_` between the two, and for good measure appends an underscore to the message type name. So for the chatter example you used above:
> ```shell
> $ ros2 topic info /chatter --verbose
> Type: std_msgs/msg/String
> ```

The name space is `std_msgs/msg` and the message type name is String, and the corresponding DDS type name is `std_msgs/msg/dds_/String_`. Like you also noticed:

> But the actual topic name "rt/chatter" and type name is "std_msgs/msg/dds_/String_"

The *topic* name is easy: it is the `rt/` prefix is, the name space and the topic name. (Services use different prefixes, but those you usually don't need to deal with directly). So here the name space is `/` and the ROS 2 topic name is `chatter` and therefore it maps to the DDS topic name `rt/chatter`.

So the rules are pretty simple, but checking with `cyclonedds ls` is often the easiest way to be certain 🙂

> If I generate the idl file below, the code is normally generated, but if I change "struct String_" to "struct String", the following error message occurs. "cyclonedds-cxx/examples/helloworld/HelloWorldData.idl:16:20: syntax error" Why did the syntax error occur?
> 
> ```
> module std_msgs {
>     module msg {
>         module dds_ {
>             struct String_ {
>                 string data;
>             };
>         };
>     };
> };
> ```
> 
> Thank you in advance.

That syntax error is because OMG IDL is case insensitive and `string` is a keyword. Our IDL compiler does have a `-f case-sensitive` option (where the keywords are all lower case) but we recommend you use it only when you have to to minimise surprises in the future.

**Comment by showmethejinw** [comment]
@eboasson, 

I fully understood, thanks to you! 
Thanks as always for your help.

Have a good day 😄
