### ISSUE TITLE
issues while crosscompiling cyclonedds-cxx for latest master cyclonedds.

### ISSUE THREAD

**Issue by RamakrishnanOSS** [eclipse-cyclonedds/cyclonedds-cxx#61]
Issues while crosscompiling cyclonedds-cxx for latest master cyclonedds.

CMake Error at src/idlcxx/CMakeLists.txt:14 (add_library):
  Target "idlcxx" links to target "CycloneDDS::idl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/idlcxx/CMakeLists.txt:14 (add_library):
  Target "idlcxx" links to target "CycloneDDS::idl" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

cross-compile for aarch64 - cmake-toolchain-file
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
SET(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_C_COMPILER "aarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "aarch64-linux-gnu-g++")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

**Comment by RamakrishnanOSS** [comment]
This is because idl is not exported by cyclonedds.
see below changes from cyclonedds/src/CMakeList.txt

```
if(NOT CMAKE_CROSSCOMPILING AND BUILD_IDLC)
  add_subdirectory(idl)
endif()
```

**Comment by RamakrishnanOSS** [comment]
Some more compilation errors.

cyclonedds-cxx/src/ddscxx/src/org/eclipse/cyclonedds/pub/AnyDataWriterDelegate.cpp:111:27: error: cannot convert ‘ddsi_sertopic*’ to ‘const ddsi_sertype*’
  111 |         td_->get_ser_topic(),
      |         ~~~~~~~~~~~~~~~~~~^~
      |                           |
      |                           ddsi_sertopic*

**Comment by eboasson** [comment]
I get that error when I combine the `idlcxx` branch of `cyclonedds-cxx` and the master branch of `cyclonedds`. @k0ekk0ek is working on it, the best thing to do is to use the `idlcxx` branch in both repositories for a couple of days longer.

**Comment by RamakrishnanOSS** [comment]
Ah... Yes.  now I used master branch of both the repos. Now I could compile. Thanks you. 

- Is there any ways to compile required tools only for cross-compiling it?

**Comment by k0ekk0ek** [comment]
Hi @RamakrishnanOSS! Thanks for giving it a try :+1: Currently, unfortunately, not. It could be a nice feature to have though, I hadn't thought about it before. Eclipse Cyclone DDS is not that big of a project in terms of lines-of-code, so it probably won't save you all that much time, but it might also not be that much work to add it. The reason that approach won't currently work though is that the compiler backend in `cyclonedds-cxx` is a plugin for the compiler in `cyclonedds` (`idlc`). Both share `libidl`, which implements a basic compiler directive and idl parser that outputs a tree-like structure which is handed over to the backend. `idlcxx` branches in both repositories have been created together to get a first version out asap for users that requested it. `libidl` and `idlc` since then have evolved to add functionality and tackle some problems. Keeping `idlcxx` up-to-date with a moving target proved rather hard, so we focused on finishing the first two parts. Basically, the backend is currently incompatible with the tree structure produced by the compiler in the master branch. The good news is that I've been working on getting the C++ backend up-to-date since and I expect a PR in the near future. I'm finishing up the last parts.

**Comment by k0ekk0ek** [comment]
@RamakrishnanOSS, I'm closing this issue since it's resolved. You may want to take a look/keep an eye on the *templated-streaming* branch. It's compatible with Cyclone DDS's master branch and should be ready in the near future.
