### ISSUE TITLE
setup github action CI

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds-cxx#7]
Please set up this CI on this repo, should probably do it for cyclonedds too @eboasson @thijssassen 
https://dev.azure.com/thijssassen/CXX-API/_build/results?buildId=227&view=results

**Comment by k0ekk0ek** [comment]
Hi @joespeed. Not sure what you mean. We use Travis CI for [cyclonedds](https://travis-ci.com/github/eclipse-cyclonedds/cyclonedds) and [cyclonedds-cxx](https://travis-ci.com/github/eclipse-cyclonedds/cyclonedds-cxx).

**Comment by joespeed** [comment]
> Hi @joespeed. Not sure what you mean. We use Travis CI for [cyclonedds](https://travis-ci.com/github/eclipse-cyclonedds/cyclonedds) and [cyclonedds-cxx](https://travis-ci.com/github/eclipse-cyclonedds/cyclonedds-cxx).

Right, but look at what @thijssassen did here for cyclonedds C++ API CI. There is tremendous value in doing this publicly in this manner for all the community to see. We actually need that for the cyclonedds quality level work that we are doing. I’m not saying don’t use Travis, I’m saying add this 
https://dev.azure.com/thijssassen/CXX-API/_build/results?buildId=227&view=results

**Comment by k0ekk0ek** [comment]
Aha. Travis CI is available publicly. Always has been really (@ThijsSassen must have had a good teacher :slightly_smiling_face: :). @ThijsSassen and I thought that maybe adding the badge to the `README.md` on the frontpage so that people notice when viewing the repository should cover it(?) The pages are more-or-less equivalent (Azure's one is perhaps a little prettier, though that's in the eye of the beholder). Anyway he went through the trouble of adding a Travis and Coverity Scan badges in PR #8, I'll merge it shortly.

**Comment by k0ekk0ek** [comment]
Btw, I should mention that we're adding the tests sometime next week. Not using `idlpp-cxx` in the builds yet because we're working on a new IDL compiler (as you probably know already?) and I didn't want to go through the trouble of getting the old one through the Eclipse IP review. `idlpp-cxx` contains large parts of OpenSplice and it didn't look like that would get through the IP review process anytime soon when we tried to get OpenSplice accepted as an Eclipse Project.

We should probably get something like [codecov](https://codecov.io/) in here as well (the necessary CMake modules are actually already approved by the Eclipse IP team) and I'd really like to have somekind of dashboard with the test results, preferably with some history, myself.

Hope the overview shows the information you want, more suggestions are of course welcome.

**Comment by k0ekk0ek** [comment]
We've been using Azure Pipelines for a while now after Travis became unusable. The idea is to integrate test and coverage results. @ThijsSassen care to open a PR?
