### ISSUE TITLE
Question concerning idl_ddscxx_generate

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds-cxx#73]
- [x] Can I call Idlcpp-cxx to generate source files and compile them into a library in a seperate cmake project using `idl_ddscxx_generate`?

Background: I basically want my project to be independent of the IDL cxx compiler. I want to have a seperate project where I only compile the IDL files. Then I want to copy the generated output (generate libraries and generated source files) to a seperate computer and use them there without having to install the IDL cxx compiler on that particular machine.

**Comment by k0ekk0ek** [comment]
Hi @Kischy. Totally understandable. That's probably because of the Java dependency right? The way we chose to solve that problem is by writing a new compiler in C based on Bison. That compiler is already in Cyclone DDS, and a new backend specifically for C++ is currently in the works (see the templated-streaming branch, or rather, #71). That'll eliminate the dependency on *idlcpp-cxx* and Java. That work will probably be merged back to the master branch shortly before we'll do the first release of the C++ binding. If you want to skip building the compiler all together then configure *cyclonedds* with `-DBUILD_IDLC=off`. For the C++ binding we'll then have to add something like `BUILD_IDLCXX` which can be toggled. For the current master though, I think you can disable building the examples. In that separate project you can provide the generated sources simply as source files, if you want to compile them in a separate project that's of course up to you and totally doable. Still, I wouldn't worry about it too much once the new backend is here. The overhead for compiling is pretty low and the new backend also introduces a new serializer that's much faster that what's on the current master branch.

**Comment by Kischy** [comment]
@k0ekk0ek Yes, because of the Java dependency. Thank you for taking the time to answer this question :)
