### ISSUE TITLE
CMAKE_BUILD_TYPE has no effect?

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds-cxx#78]
When I run 
`cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="D:/EclipseCylconeDDS/cyclonedds-cxx/install" -DCMAKE_PREFIX_PATH="D:/EclipseCylconeDDS/idlpp-cxx/install;D:/EclipseCylconeDDS/cyclonedds/install" -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF .. && cmake --build . -j --target install`

or 
`cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX="D:/EclipseCylconeDDS/cyclonedds-cxx/install_32" -DCMAKE_PREFIX_PATH="D:/EclipseCylconeDDS/idlpp-cxx/install;D:/EclipseCylconeDDS/cyclonedds/install_32" -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF .. && cmake --build . -j --target install`

I get the following warning

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
```

Apparently `-DCMAKE_BUILD_TYPE=Release` has no effect. What am I doing wrong here?

**Comment by eboasson** [comment]
It is a quirk of CMake, the `CMAKE_BUILD_TYPE` only (?) affects the `make` and `ninja` generators. For the Visual Studio generators, it always generates all configurations and you have to specify the configuration when you do the actual build step. If you don't specify one, it'll pick one (which seem to always be Debug, I assume because the D comes before the R in the alphabet, but you know what they say about assumptions!).

For the Cyclone CI, we do that by building using `cmake --build . --config Release` (see https://github.com/eclipse-cyclonedds/cyclonedds/blob/9e0d5bc69f83795e0b0855c2e4afdeecfd6b687c/.azure/templates/build-test.yml#L102). Perhaps also useful is https://stackoverflow.com/questions/19024259/how-to-change-the-build-type-to-release-mode-in-cmake

(As an aside, I've discovered that `ninja` also works on Windows and is much more pleasant to work with than the visual studio-based build system.)

**Comment by Kischy** [comment]
Arg, that is unintuitive. Thank you!
